---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml

  tasks:
  #Creates group Developers
  - name: Creating Developers group
    when: ansible_facts['distribution'] == "Ubuntu"
    group:
      name: "{{ item }}"
      state: present
    loop: "{{ dev_groups }}"

    # Create 5 users, add to devops group and ssh keys
  - name: Create 5 users - add to Developers group - generate ssh keys
    when: ansible_facts['distribution'] == "Ubuntu"    
    user:
      name: "{{ item }}"
      groups: "{{ dev_groups }}"
      generate_ssh_key: yes
      append: yes
      state: present
    loop: "{{ dev_users }}"



    # Allow admin group users to have sudo priviledge
  - name: "Allow admin users to sudo without a password"
    when: ansible_facts['distribution'] == "Ubuntu"    
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"










      # - hosts: all
#   become: true
  
#   tasks:

#   - name: Creating DevOps group
#     when: ansible_facts['distribution'] == "Ubuntu"
#     group:
#       name: "{{ item }}"
#       state: present
#     loop:
#       - devops
#       - admin

#   - name: Create 5 users - add to DevOps group - generate ssh keys
#     when: ansible_facts['distribution'] == "Ubuntu"    
#     user:
#       name: "{{ item }}"
#       groups: devops, admin
#       generate_ssh_key: yes
#       append: yes
#       state: present
#     with_items:
#       - angel
#       - david
#       - burrito
#       - sadko
#       - clarus      

#   - name: "Allow admin users to sudo without a password"
#     when: ansible_facts['distribution'] == "Ubuntu"    
#     lineinfile:
#       dest: "/etc/sudoers" # path: in version 2.3
#       state: "present"
#       regexp: "^%admin"
#       line: "%admin ALL=(ALL) NOPASSWD: ALL"

